### ISSUE TITLE
Little Drawing error

### ISSUE THREAD

**Issue by Ulf-Ha** [ItKindaWorks/ESP8266#2]
Hello,
If the reed switch closes - then it would shotcut the power ?
https://github.com/ItKindaWorks/ESP8266/blob/master/Home%20Automation/Part%204/Breadboard%20Layouts/ESP%20Nodes.fzz

UHA

**Comment by ItKindaWorks** [comment]
Thanks! It would have shorted to power youre right. Corrected to connect from GND to pin 2 where the switch should be.

**Comment by Ulf-Ha** [comment]
now ist better to understand for me :) - thanks
